apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: idp-infra
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:woletokun/idp.git
    targetRevision: main
    path: infra   # points to infra manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: infra   # deploys into infra namespace
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
