apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: idp-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:woletokun/idp.git
    targetRevision: main
    path: apps
  destination:
    server: https://kubernetes.default.svc
    namespace: apps
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: linkedin-scraper
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/woletokun/idp.git'
    targetRevision: main
    path: apps/linkedin-scraper
  destination:
    server: https://kubernetes.default.svc
    namespace: apps
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
