---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgres-secret
  namespace: apps
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgAZcLPStsYIqCnuhZS424i8JSeY8l6s9zPd27MWkJq33Yoc2DByesr+jwwBuME4A2TckWONJ20WSxa2hCbXAx5PgYNWOR1b0c+61cjWj3t4Bg0c6GX3ZTR73UvT3SHwuAYsvPZ4S3tGEuwuKy1kskWjiy6yIDYmGv1pWBr9MEEgRRCRUNvcm6oBepg4DJxlPnDRsC8wp0u44ghtVpyhakCEH4MF+1vD0lBHoqsuepJ7AZMDQjfuAUpmVkAPXVfUte3+wr9bSqx5AxPQokz9FteKCiXnBMeI9FStB4bEKPjFpfZLQHai8xJE6KwcqHtt7Vn7wbIF0wMYiHLDdtIofM6BuiJTDjrqNCcTc7hVUZHrNmGibnx6394IRgt5Rxi8usXze+VWHFJNm3PK0NlJ+pXafMv4l/IIW2nLk0k1/TVFfDdLy/CBrZn4EQmp0Qm+Vl6vJxpHQwsuXSeuusZ70qL1jlOaMirMYau6Gux3PKKrvNbh6C5g+WK33gsaTZBcCmJgbBReR3f5Y4T+pDMzFFZWH05OqT7sNlKz9JKxaDgqUH/EiYaOQSkuQXsxajb8UrzavK3FxGmISoSt/GKpjHxAecWc8wm/J3zLuJYVWFNOCjVLwmbumZiqlj+M5eWbiT5EFufqeWPDqBsyNE8kjLL8oOl6M/1YI6u2Znzbshg8hQeK7hEJWqNYjn3eFYm1Wzy8FAwVMShiANjaVhLATA==
  template:
    metadata:
      creationTimestamp: null
      name: postgres-secret
      namespace: apps
