apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: adminer
  namespace: apps

spec:
  ingressClassName: traefik
  rules:
  - host: adminer.mycluster.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: adminer
            port:
              number: 8080
