---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgres-secret
  namespace: infra
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgCYjUfWQ8rFNzlM2/BpH1KKpyDARgrltW9HHAXRETxlzIk3SeAbkHFT/bKCqzxyhf5eDRc0Hp5iGTnx8qVhNrVravj2fIhKz3t5YEtjD4RszRxB27Jbag2wJOMdvTbrKrjbbj4YVG2a9UAHOFBF+9OHr5N8DeDsHWSzYuph33afSEVORQspsJW0BW0AT3e5yzRoXDojJyOIFbwAmaya0Ox0ljtLLl9hqA3/wzrhgr29SybIoflxv64Wz4GtyBA4Fh9N3V+65XTnATrz3lkHBAJqQtupkalgVrcgaDq0Z+JecVYSb+qXN7CbUjJdsgExdYuGLj+yIeqPuhFKIYziB1PioU2WAXOZtDLSzQ42lPhSjbvF0bar4mhv2EYY9brKyk7oHoAuDzI7RG41iN9xlBUFloNwtGLfFTL47sUbLDltG61nac6gb37OYmZmriU/uliO2gpCjuIVYnz40iwxyff358QkyqGwNQ24vU52ifEbzL/VsGAgUobNHh70lAZpdG+zOEzcKSeJ4+w2w4i4pFhCUgPeRikhup/KThr/sFl056xIauCwbUBm/B1HO3VQuemqWzdY5QFYApA6fnrXTzyYUHjMToYutFEmUFpxCClvJW1iZEPIIZsZI1mgZpbnVPQigT6ZvaxF3v+hM3ZNHLWniD9c5Hd4/kx3ynb58ijO9SIBJV3Vx4LDv1C0/SiX6uICQazc/AFdnbb/g3Felw==
  template:
    metadata:
      creationTimestamp: null
      name: postgres-secret
      namespace: infra
