apiVersion: apps/v1
kind: Deployment
metadata:
  name: linkedin-scraper
  namespace: apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: linkedin-scraper
  template:
    metadata:
      labels:
        app: linkedin-scraper
    spec:
      containers:
      - name: scraper
        image: tokstokun/linkedin-scraper:latest   # <-- your actual DockerHub repo
        imagePullPolicy: Always                   # ensures Kubernetes always fetches the latest
        imagePullSecrets:
          - name: regcred

        ports:
        - containerPort: 8080
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_USER
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_DB
        - name: POSTGRES_HOST
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_HOST
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_PASSWORD
