apiVersion: batch/v1
kind: CronJob
metadata:
  name: linkedin-scraper
  namespace: apps
spec:
  schedule: "0 0 * * *"   # every day at midnight
  timeZone: Africa/Lagos  # run at local midnight
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: scraper
            image: tokstokun/linkedin-scraper:latest
            imagePullPolicy: Always
            env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_DB
            - name: POSTGRES_HOST
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_HOST
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
          restartPolicy: Never
