name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: pip install -r apps/linkedin-scraper/requirements.txt

    - name: Run tests
      run: pytest apps/linkedin-scraper/tests/

    - name: Build Docker image
      run: docker build -t ghcr.io/woletokun/idp:latest apps/linkedin-scraper/

    - name: Push Docker image
      run: |
        echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
        docker push ghcr.io/woletokun/idp:latest

    - name: Prepare kubeconfig
      run: mkdir -p $HOME/.kube
    
    - name: Set up kubeconfig
      run: |
        echo "${{ secrets.KUBECONFIG_DATA }}" > $HOME/.kube/config


  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'v1.29.0'

    - name: Deploy to cluster
      run: |
        kubectl apply -f infra/
        kubectl apply -f apps/linkedin-scraper/
